# Generated by Django 4.2 on 2024-05-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAulas',
            fields=[
                ('IdArchivoSeguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCoordinador', models.CharField(max_length=100)),
                ('ArchivoSeguimiento', models.FileField(upload_to='uploads/')),
                ('IdProceso', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'SeguimientoAulas',
                'managed': True,
            },
        ),
    ]
